name: Sync GeoIP Data

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 22 * * *' # 每天 UTC 时间凌晨 1 点运行，您可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予对仓库内容的写入权限，用于git push

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Clone MetaCubeX/meta-rules-dat repository
      run: |
        git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git meta-rules-dat-temp

    - name: Copy geoip folder
      run: |
        mkdir -p Surge/geoip # 确保目标文件夹存在
        cp -r meta-rules-dat-temp/geo/geoip/. Surge/geoip/

    - name: Process .list files with IP prefixes
      run: |
        # 正则表达式用于匹配 IPv4 和 IPv6
        # IPv4: 0.0.0.0 - 255.255.255.255, 允许可选的 /CIDR
        IPV4_REGEX="^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$"
        # IPv6: 典型的 IPv6 格式，允许可选的 /CIDR
        IPV6_REGEX="^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}(/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8]))?$"
        IPV6_SHORT_REGEX="^((([0-9A-Fa-f]{1,4}:){1,6}:)|([0-9A-Fa-f]{1,4}:)*:[0-9A-Fa-f]{1,4})((/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8]))|/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8]))?$"
        
        find Surge/geoip -name "*.list" -print0 | while IFS= read -r -d $'\0' file; do
          echo "Processing file: $file"
          # 使用awk进行处理
          awk -v ipv4_regex="$IPV4_REGEX" -v ipv6_regex="$IPV6_SHORT_REGEX" '{
            if ($0 ~ ipv4_regex) {
              print "IP-CIDR," $0
            } else if ($0 ~ ipv6_regex) {
              print "IP-CIDR6," $0
            } else {
              # 如果不匹配IPv4或IPv6，保持原样，或者您可以选择跳过/删除这些行
              print $0
            }
          }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Surge/geoip
        git diff-index --quiet HEAD || git commit -m "chore(geoip): Sync and process geoip data with prefixes"
        git push
