name: Sync Geosite Lists

on:
  schedule:
    - cron: '0 3 * * *'   # 每天 03:00 UTC 运行
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download geosite lists
        run: |
          BASE_URL="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite"
          FILES=$(curl -s https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/geo/geosite?ref=meta | jq -r '.[] | select(.name|endswith(".list")) | .name')
          for file in $FILES; do
            echo "Downloading $file ..."
            curl -s "${BASE_URL}/${file}" | sed 's/^+//' > "Surge/geosite/${file}"
          done
