name: Sync GeoIP Data

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 22 * * *' # 每天 UTC 时间凌晨 1 点运行，您可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予对仓库内容的写入权限，用于git push

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Clone MetaCubeX/meta-rules-dat repository
      run: |
        git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git meta-rules-dat-temp

    - name: Copy geoip folder
      run: |
        mkdir -p Surge/geoip # 确保目标文件夹存在
        cp -r meta-rules-dat-temp/geo/geoip/. Surge/geoip/

    - name: Process .list files with IP prefixes
      run: |
        # 简单判断是否包含 . 或 : 来区分 IPv4 和 IPv6
        find Surge/geoip -name "*.list" -print0 | while IFS= read -r -d $'\0' file; do
          echo "Processing file: $file"
          awk '!/^(\s*#|\s*\/\/)/ {
            if ($0 ~ /\./) {
              print "IP-CIDR," $0
            } else if ($0 ~ /:/) {
              print "IP-CIDR6," $0
            } else {
              print $0
            }
          }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        shopt -s globstar
        git add Surge/geoip/**/*.list
        git diff --cached --quiet || git commit -m "chore(geoip): Sync and process geoip .list files"
        git push
