name: Sync Geosite Data

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行，您可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest
	permissions:
      contents: write # 授予对仓库内容的写入权限，用于git push

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Set up Node.js (for file processing)
      uses: actions/setup-node@v4
      with:
        node-version: '18' # 或者其他您偏好的 Node.js 版本

    - name: Clone MetaCubeX/meta-rules-dat repository
      run: |
        git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git meta-rules-dat-temp

    - name: Copy geosite folder
      run: |
        mkdir -p Surge/geosite # 确保目标文件夹存在
        cp -r meta-rules-dat-temp/geo/geosite/. Surge/geosite/

    - name: Process .list files
      run: |
        find Surge/geosite -name "*.list" -print0 | while IFS= read -r -d $'\0' file; do
          echo "Processing file: $file"
          # 使用awk处理文件，如果行以'+'开头，则删除'+'
          # 如果不以'+'开头，则保持不变
          awk '{ if (substr($0, 1, 1) == "+") print substr($0, 2); else print $0 }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Surge/geosite
        git diff-index --quiet HEAD || git commit -m "chore(geosite): Sync and process geosite data"
        git push
